# Generated by Django 5.1.2 on 2024-12-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='caregory',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
