# Generated by Django 5.1.2 on 2024-12-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner2',
            name='product',
        ),
        migrations.AddField(
            model_name='banner2',
            name='b_dis',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner2',
            name='b_name',
            field=models.TextField(default='id'),
            preserve_default=False,
        ),
    ]
