# Generated by Django 5.1.2 on 2024-12-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_caregory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic1', models.FileField(upload_to='')),
                ('pic2', models.FileField(upload_to='')),
                ('pic3', models.FileField(upload_to='')),
            ],
        ),
    ]
