# Generated by Django 5.1.2 on 2024-12-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_category_alter_product_caregory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caregory',
            new_name='category',
        ),
    ]
