# Generated by Django 5.1.2 on 2024-12-30 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_buy_address_buy_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
